services:
  - type: web
    name: Hand-Receipt-Generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn HrApp5:app
    envVars:
      - key: FLASK_ENV
        value: production
